import { useDeleteUser } from '@core/presentation/hooks/use-delete-user';
import { User } from '@domain/dtos/user';
import {
  DeleteButton,
  Table,
  TableCells,
  UserForm,
} from '@presentation/components';
import { useListUsers } from '@presentation/hooks/use-list-users';
import Head from 'next/head';

const Home = (): JSX.Element => {
  const listUsers = useListUsers();
  const deleteUser = useDeleteUser({
    cb: {
      success: listUsers.refetch,
    },
  });

  const cells: TableCells<User> = [
    {
      label: 'Id',
      content: (user) => user.id.toString(),
    },
    {
      label: 'Name',
      content: (user) => user.name,
    },
    {
      label: 'Email',
      content: (user) => user.email,
    },
    {
      label: 'Actions',
      content: (user) => (
        <DeleteButton
          data-cy={`button-delete-${user.email}`}
          onClick={() => deleteUser.mutate(user)}
        />
      ),
    },
  ];

  return (
    <>
      <Head>
        <title>User App Control</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex justify-center">
          <div className="w-3/5 p-8">
            <h1 className="pb-2 text-3xl font-bold">User App Control</h1>
            <UserForm onSave={listUsers.refetch} />
            <Table
              cells={cells}
              isLoading={listUsers.isFetching}
              isUpdating={deleteUser.isLoading}
              rows={listUsers.data}
            />
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
